# Generated by Django 2.2.5 on 2019-09-28 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorological_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Meteorological_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_max', models.FloatField(null=True)),
                ('T_min', models.FloatField(null=True)),
                ('RH_max', models.FloatField(null=True)),
                ('RH_min', models.FloatField(null=True)),
                ('Rn', models.FloatField(null=True)),
                ('U', models.FloatField(null=True)),
                ('P', models.FloatField(null=True)),
                ('Ri', models.FloatField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Meteorological_Station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.Meteorological_Station', verbose_name='Estação Meteorológica')),
            ],
        ),
    ]
